AWSTemplateFormatVersion: 2010-09-09
Description: Lambda Deployment

Parameters:
  bucket:
    Type: String
  environment:
    Type: String

Resources:
  TheLambdaManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'The-Lambda-Policy-${environment}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: logs:CreateLogGroup
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource:
            - arn:aws:logs:*:*:log-group:/aws/lambda/lambda_test:*

  TheLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'TheLambdaRole-${environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Ref TheLambdaManagedPolicy

  TheLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'The-Function-${environment}'
      Handler: hello.handler
      Role: !GetAtt TheLambdaRole.Arn
      Code:
        S3Bucket: !Ref bucket
        S3Key: deploy.zip
      Runtime: provided.al2 

  FunctionUrl:
    Type: AWS::Lambda::Url
    Properties: 
      AuthType: NONE
      TargetFunctionArn: !Ref TheLambdaFunction

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunctionUrl
      FunctionName: !Ref TheLambdaFunction
      FunctionUrlAuthType: NONE
      Principal: "*"
