name: Deploy

on:
  push:
    branches:
    - dev
    - main

env:
  LAMBDA_STACK_NAME: Lambda-Stack-${{ github.ref_name }}
  S3_STACK_NAME: S3-Stack-${{ github.ref_name }}
  LAMBDA_BUCKET: lambda-bucket-keug-${{ github.ref_name }}
  FUNCTION_NAME: The-Function-${{ github.ref_name }}
  ENVIRONMENT: ${{ github.ref_name }}

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Deploy CFT for S3 Bucket
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: ${{ env.S3_STACK_NAME }}
          template: cft/s3_cft.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            bucket=${{ env.LAMBDA_BUCKET }}
      - name: zip and sync
        run: |
          zip -j deploy.zip ./functions/*
          aws s3 cp deploy.zip s3://${{ env.LAMBDA_BUCKET }}/
      - name: Deploy CFT for lambda function
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: ${{ env.LAMBDA_STACK_NAME }}
          template: cft/lambda_cft.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: >-
            bucket=${{ env.LAMBDA_BUCKET }},
            environment=${{ env.ENVIRONMENT }},
            function_name=${{ env.FUNCTION_NAME }}
      - name: redeploy lambda if needed, as CFT wont do it on a code change
        run: |
          aws lambda update-function-code --function-name=${{ env.FUNCTION_NAME }} --s3-bucket ${{ env.LAMBDA_BUCKET }} --s3-key deploy.zip
